name: deploy to vercel
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install vercel cli
        run: npm install --global vercel
      - name: pull veribals and settings from vercel server
        run: vercel pull --yes --environment=production --token=${{secrets.VERSEL_TOKEN}}
      - name: build the artifacts
        run: vercel build --prod --token=${{secrets.VERSEL_TOKEN}}
      - name: deploy the artifact
        run: vercel --prebuilt --prod --token=${{secrets.VERSEL_TOKEN}}
        

